In [1]:
import torch
torch.__version__

'2.0.0'

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# Check the number of dimensions of vector
vector.ndim

1

In [7]:
# Check shape of vector
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# Check number of dimensions
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [13]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

#### **NOTE**
- scalar : Lower(a)
- vector : Lower(y)
- matrix : Upper(Q)
- tensor : Upper(X)

## Create a random tensors

Neural Network:
Start with random number -> look at data -> adjust random numbers -> look at data -> ...

In [14]:
random_tensor = torch.rand(1, 3, 3)
random_tensor

tensor([[[0.4625, 0.6650, 0.9850],
         [0.3922, 0.6144, 0.0934],
         [0.7745, 0.7141, 0.2673]]])

In [15]:
random_tensor.ndim

3

In [16]:
random_tensor.shape

torch.Size([1, 3, 3])

In [17]:
# Create a random tensor with similar with shape to an image tensor
rand_img_size_tensor = torch.rand(size=(3, 180, 180))
rand_img_size_tensor.shape, rand_img_size_tensor.ndim

(torch.Size([3, 180, 180]), 3)

## Zeros and ones

In [18]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
random_tensor.dtype

torch.float32

## Create a range of tensors and tensors-like 

In [21]:
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [22]:
torch.zeros_like(random_tensor)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [23]:
torch.ones_like(random_tensor)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

## Tensor datatypes

In [24]:
float32_tensor = torch.tensor([3., 6., 9.], dtype=None, device=None, requires_grad=False)
float32_tensor

tensor([3., 6., 9.])

In [25]:
float32_tensor.dtype

torch.float32

In [26]:
float16_tensor = torch.tensor([3., 6., 9.], dtype=torch.float16, device=None, requires_grad=False)
float16_tensor.dtype 

torch.float16

In [27]:
float32_tensor.type(torch.float16)

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
(float32_tensor * float16_tensor).dtype

torch.float32

In [29]:
int32_tensor = float16_tensor.type(torch.int32)
int32_tensor.dtype

torch.int32

In [30]:
(float32_tensor * int32_tensor).dtype

torch.float32

Get information from a tensor
- Type: 'tensor.dtype'
- Shape: 'tensor.shape'
- Device: 'tensor.device'

## Tensor Operations

- Addition
- Subtraction
- Multiplication
- Division
- Production (Matrix) 

In [31]:
tensor = torch.tensor([1, 2, 3])
tensor.dtype

torch.int64

In [32]:
add, _ = tensor + 10, torch.add(tensor, 10)
add

tensor([11, 12, 13])

In [33]:
sub, _ = tensor - 10, torch.sub(tensor, 10)
sub

tensor([-9, -8, -7])

In [34]:
mul, _ = tensor * 10, torch.mul(tensor, 10)
mul

tensor([10, 20, 30])

In [35]:
div, _ = tensor / 10, torch.div(tensor, 10)
div, div.dtype

(tensor([0.1000, 0.2000, 0.3000]), torch.float32)

### Matrix multiplication 

**Rule:**
- The inner dimensions must match
    > `(a, x) . (x, b)` : x is the inner dimension
- The result matrix has the shape of outer dimensions
    > `(y, c) . (d, y) = (y, y)` : y is the outer dimension

In [36]:
tensor * tensor

tensor([1, 4, 9])

In [37]:
# dot product
torch.matmul(tensor, tensor)

tensor(14)

### Matrix transpose

In [38]:
tensor = torch.rand(2, 3)
tensor, tensor.shape

(tensor([[0.6859, 0.3399, 0.8676],
         [0.8935, 0.3074, 0.7009]]),
 torch.Size([2, 3]))

In [39]:
tensor.T, tensor.T.shape

(tensor([[0.6859, 0.8935],
         [0.3399, 0.3074],
         [0.8676, 0.7009]]),
 torch.Size([3, 2]))

### Find Min, Max, Mean, Sum, etc

In [40]:
x = torch.arange(0, 100, 10)

In [41]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [42]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [43]:
print(x.dtype)
torch.mean(x, dtype=torch.float32), x.type(torch.float32).mean()

torch.int64


(tensor(45.), tensor(45.))

In [44]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Find min and max position

In [45]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [47]:
x[0], x[9]

(tensor(0), tensor(90))

### Reshape, view, staking, squeezing and unsqueezing tensors

- reshape : reshape an input tensor to a defined shape
- view : return a view of an input tensor of certain shape but keep the same memory as the original tensor
- staking : combine multiple tensors on top of each other (vstack) or side by side (hstack)
- squeeze : removes single dimensions from a tensor
- unsqueeze : add single dimension to a tensor
- permute : return a view of the input with dimensions permuted (swapped) in a certain way

In [48]:
x = torch.arange(0., 10.)
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [49]:
x.reshape(10, 1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [50]:
# the shape output must be relative
x.reshape(5, 2)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [51]:
# view of a tensor shares the same memory as the original
# while reshape is copy of the memory
z = x.view(2, 5)
z[0][0] = 10
x

tensor([10.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [52]:
# stack tensors on top of each other
torch.vstack([x, x, x])  # same as torch.stack()

tensor([[10.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [53]:
# stack tensors next to each other
torch.hstack([x, x, x])

tensor([10.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  1.,  2.,  3.,
         4.,  5.,  6.,  7.,  8.,  9., 10.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,
         8.,  9.])

In [54]:
# squeeze : remove all single dimensions from a target tensor
x = torch.rand(1, 9)
x.shape

torch.Size([1, 9])

In [55]:
z = x.squeeze()  # or torch.squeeze()
z.shape

torch.Size([9])

In [56]:
# unsqueeze : add dimensions to a tensor
z.unsqueeze(dim=0).shape

torch.Size([1, 9])

In [57]:
# permute : rearranges the dimensions of a target tensor in a specified order
x = torch.rand(1, 2, 3)
x.shape

torch.Size([1, 2, 3])

In [58]:
# same as torch.permute(x, dims=())
# permute will work same as view so changing the assigned may also change the original
x.permute(dims=(1, 2, 0)).shape

torch.Size([2, 3, 1])

## Indexing (select data from tensors)
> similar to indexing with Numpy

In [59]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [60]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [61]:
x[0, :, :], x[0, 0, :], x[0, 0, 0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [62]:
x[-1, -1, -1]

tensor(9)

In [63]:
x[0, :, -1]

tensor([3, 6, 9])